name: Deployment pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_LOOMY_TOKEN }}
  VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
  VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY: ${{ secrets.VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          echo "Dependencies installed correctly"

      # - name: Run test
      #   run: |
      #     pnpm run test
      #     echo "Test passed successfully, proceeding to deploy"

      - name: Install Vercel CLI
        run: |
          npm install --global vercel@latest
          echo "Vercel CLI installed successfully"

      - name: Pull Vercel Environment Information (Preview)
        if: github.event_name == 'pull_request'
        run: |
          vercel pull --yes --environment=preview
          echo "Vercel Environment Information pulled successfully"

      - name: Build Project Artifacts (Preview)
        if: github.event_name == 'pull_request'
        run: vercel build

      - name: Deploy Project Artifacts to Vercel (Preview)
        if: github.event_name == 'pull_request'
        run: vercel deploy --prebuilt

      - name: Pull Vercel Environment Information (Production)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          vercel pull --yes --environment=production
          echo "Vercel Environment Information pulled successfully"

      - name: Build Project Artifacts (Production)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          vercel build --prod
          echo "Project Artifacts built successfully"

      - name: Deploy Project Artifacts to Vercel (Production)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          vercel deploy --prebuilt --prod
          echo "Project Artifacts deployed successfully 🚀"
